### ISSUE TITLE
Вопрос по Autoload

### ISSUE THREAD

**Issue by shoman4eg** [may-cat/maycat.d7dull#2]
А зачем 2 раза писать в autoload ?

``` php
'Maycat\D7dull\Model' => 'lib/model.php',
'\Maycat\D7dull\Model' => 'lib/model.php',
```

Одного раза достаточно

**Comment by im-denisenko** [comment]
Дублирование присутствовало в самых ранних примерах, когда новый автолоадер был только добавлен, возможно, что надо было из-за его сырости.

Исправлено в #3, если он будет принят.
